title: 小菜鸡的CTF题解站  
author: kslzzzzzz
description: 记录CTF解题过程与思路 
remote_theme: mmistakes/minimal-mistakes  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: "dark"   
permalink: /posts/:title/  
head_scripts:
  - /assets/css/custom.css
